spring:
  application:
    name: customer-support-platform

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/support_platform
    username: ${DB_USERNAME:support_user}
    password: ${DB_PASSWORD:support_password}
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    listener:
      ack-mode: record

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: support-platform
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.aneesh.support.ticket
        spring.json.value.default.type: com.aneesh.support.ticket.TicketCreatedEvent

logging:
  level:
    root: INFO
    com.aneesh.support: INFO
    org.springframework.kafka: INFO